/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0000,    1, "(null)",              0, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0001,    4, "x-bar",            7500, 0x1e80,     0x01, NULL,
		{
			OOO_ ,
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0002,    5, "y-bar",            7900, 0x0233,     0x02, NULL,
		{
			OOOO_ ,
			_____ ,
			O__O_ ,
			_O_O_ ,
			__O__ ,
			OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0003,    6, "sqrt",            17100, 0x221a,     0x03, NULL,
		{
			__OOO_ ,
			__O___ ,
			__O___ ,
			O_O___ ,
			_OO___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0004,    6, "integral",        17200, 0x222b,     0x04, NULL,
		{
			___O__ ,
			__O_O_ ,
			__O___ ,
			__O___ ,
			O_O___ ,
			_O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0005,    4, "degree",           1000, 0x00b0,     0xb0, NULL,
		{
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0006,    1, "narrow-space",        0, 0x00a0,     0xa0, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0007,    6, "grad",            18000, 0x24bc,     0x07, NULL,
		{
			______ ,
			_OOO__ ,
			O_____ ,
			O_OO__ ,
			O__O__ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0010,    6, "+/-",             12700, 0x00b1,     0xb1, "plus-minus",
		{
			______ ,
			__O___ ,
			OOOOO_ ,
			__O___ ,
			______ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0011,    5, "<=",              15600, 0x2264,     0xab, "le",
		{
			___O_ ,
			__O__ ,
			_O___ ,
			OOOO_ ,
			_____ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0012,    5, ">=",              16000, 0x2265,     0xbb, "ge",
		{
			O____ ,
			_O___ ,
			__O__ ,
			OOOO_ ,
			_____ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0013,    6, "!=",              15900, 0x2260,     0x87, "ne",
		{
			______ ,
			___O__ ,
			OOOOO_ ,
			__O___ ,
			OOOOO_ ,
			_O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0014,    6, "euro",            16400, 0x20ac,     0x80, NULL,
		{
			__OOO_ ,
			_O____ ,
			_OOO__ ,
			OOO___ ,
			_O____ ,
			__OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0015,    6, "->",              14600, 0x2192,     0x05, "right",
		{
			______ ,
			__O___ ,
			___O__ ,
			OOOOO_ ,
			___O__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0016,    6, "<-",              14700, 0x2190,     0x06, "left",
		{
			______ ,
			__O___ ,
			_O____ ,
			OOOOO_ ,
			_O____ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0017,    6, "v",               14900, 0x2193,     0x0f, "down",
		{
			______ ,
			__O___ ,
			__O___ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0020,    6, "^",               14800, 0x2191,     0x10, "up",
		{
			______ ,
			__O___ ,
			_OOO__ ,
			O_O_O_ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0021,    5, "f-shift",           100, 0x24d5,     0x11, NULL,
		{
			__OO_ ,
			_O___ ,
			OOO__ ,
			_O___ ,
			_O___ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0022,    5, "g-shift",           200, 0x24d6,     0x12, NULL,
		{
			_OOO_ ,
			O__O_ ,
			_OOO_ ,
			___O_ ,
			OOO__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0023,    5, "h-shift",           300, 0x24d7,     0x13, NULL,
		{
			O____ ,
			O____ ,
			OOO__ ,
			O__O_ ,
			O__O_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0024,    3, "cmplx",            2700, 0x00a9,     0xa9, NULL,
		{
			OO_ ,
			O__ ,
			OO_ ,
			___ ,
			___ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0025,    6, "O-slash",          5800, 0x00d8,     0xd8, NULL,
		{
			_OOOO_ ,
			O__OO_ ,
			O_O_O_ ,
			O_O_O_ ,
			OO__O_ ,
			OOOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0026,    5, "o-slash",          5800, 0x00f8,     0xf8, NULL,
		{
			_____ ,
			_____ ,
			_OOO_ ,
			O_OO_ ,
			OO_O_ ,
			OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0027,    6, "<->",             15200, 0x21c6,     0x17, "exchange",
		{
			_O____ ,
			OOOOO_ ,
			_O____ ,
			___O__ ,
			OOOOO_ ,
			___O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0030,    5, "sz",               6400, 0x00df,     0xdf, NULL,
		{
			_OO__ ,
			O__O_ ,
			OOO__ ,
			O__O_ ,
			OOOO_ ,
			O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0031,    4, "x-hat",            7600, 0x1e8b,     0x19, NULL,
		{
			_O__ ,
			O_O_ ,
			____ ,
			O_O_ ,
			_O__ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0032,    4, "y-hat",            8100, 0x0177,     0x1a, NULL,
		{
			_O__ ,
			O_O_ ,
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0033,    6, "sub-m",            5000, 0x2098,     0x1b, NULL,
		{
			______ ,
			______ ,
			______ ,
			______ ,
			OOOOO_ ,
			O_O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0034,    4, "times",           12500, 0x00d7,     0xd7, NULL,
		{
			____ ,
			____ ,
			O_O_ ,
			_O__ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0035,    5, "approx",          15800, 0x2248,     0x1d, NULL,
		{
			_____ ,
			_O_O_ ,
			O_O__ ,
			_____ ,
			_O_O_ ,
			O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0036,    5, "pound",           16500, 0x00a3,     0xa3, NULL,
		{
			__O__ ,
			_O_O_ ,
			_O___ ,
			OOO__ ,
			_O___ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0037,    6, "yen",             16600, 0x00a5,     0xa5, NULL,
		{
			O___O_ ,
			_O_O__ ,
			_OOO__ ,
			__O___ ,
			_OOO__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0040,    5, "space",               0, 0x0020,     0x20, NULL,
		{
			_____ ,
			_____ ,
			_____ ,
			_____ ,
			_____ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0041,    2, "!",               13000, 0x0021,     0x21, "exclam",
		{
			O_ ,
			O_ ,
			O_ ,
			O_ ,
			__ ,
			O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0042,    4, "dbl-quote",       13500, 0x0022,     0x22, "quotedbl",
		{
			O_O_ ,
			O_O_ ,
			____ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0043,    6, "#",               25500, 0x0023,     0x23, "numbersign",
		{
			______ ,
			_O_O__ ,
			OOOOO_ ,
			_O_O__ ,
			OOOOO_ ,
			_O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0044,    6, "$",               16300, 0x0024,     0x24, "dollar",
		{
			__O___ ,
			_OOOO_ ,
			O_O___ ,
			_OOO__ ,
			__O_O_ ,
			OOOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0045,    6, "%",               16200, 0x0025,     0x25, "percent",
		{
			______ ,
			OO__O_ ,
			OO_O__ ,
			__O___ ,
			_O_OO_ ,
			O__OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0046,    6, "&",               17600, 0x0026,     0x26, "ampersand",
		{
			_OO___ ,
			O__O__ ,
			_OO___ ,
			O__OO_ ,
			O__O__ ,
			_OO_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0047,    2, "'",               13400, 0x0027,     0x27, "quotesingle",
		{
			O_ ,
			O_ ,
			__ ,
			__ ,
			__ ,
			__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0050,    3, "(",               12100, 0x0028,     0x28, "parenleft",
		{
			_O_ ,
			O__ ,
			O__ ,
			O__ ,
			O__ ,
			_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0051,    3, ")",               12200, 0x0029,     0x29, "parenright",
		{
			O__ ,
			_O_ ,
			_O_ ,
			_O_ ,
			_O_ ,
			O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0052,    6, "*",               13700, 0x002a,     0x2a, "asterisk",
		{
			_O_O__ ,
			__O___ ,
			OOOOO_ ,
			__O___ ,
			_O_O__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0053,    6, "+",               12300, 0x002b,     0x2b, "plus",
		{
			______ ,
			__O___ ,
			__O___ ,
			OOOOO_ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0054,    3, ",",               12800, 0x002c,     0x2c, "comma",
		{
			___ ,
			___ ,
			___ ,
			OO_ ,
			_O_ ,
			O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0055,    6, "-",               12400, 0x002d,     0x2d, "hyphen",
		{
			______ ,
			______ ,
			______ ,
			OOOOO_ ,
			______ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0056,    3, ".",               12900, 0x002e,     0x2e, "period",
		{
			___ ,
			___ ,
			___ ,
			___ ,
			OO_ ,
			OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0057,    4, "/",               12600, 0x002f,     0x2f, "slash",
		{
			__O_ ,
			__O_ ,
			_O__ ,
			_O__ ,
			O___ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0060,    5, "0",                1000, 0x0030,     0x30, "zero",
		{
			_OO__ ,
			O__O_ ,
			O_OO_ ,
			OO_O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0061,    3, "1",                1100, 0x0031,     0x31, "one",
		{
			_O_ ,
			OO_ ,
			_O_ ,
			_O_ ,
			_O_ ,
			_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0062,    5, "2",                1200, 0x0032,     0x32, "two",
		{
			_OO__ ,
			O__O_ ,
			___O_ ,
			__O__ ,
			_O___ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0063,    5, "3",                1300, 0x0033,     0x33, "three",
		{
			OOOO_ ,
			___O_ ,
			__O__ ,
			___O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0064,    5, "4",                1400, 0x0034,     0x34, "four",
		{
			O_O__ ,
			O_O__ ,
			O_O__ ,
			OOOO_ ,
			__O__ ,
			__O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0065,    5, "5",                1500, 0x0035,     0x35, "five",
		{
			OOOO_ ,
			O____ ,
			OOO__ ,
			___O_ ,
			___O_ ,
			OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0066,    5, "6",                1600, 0x0036,     0x36, "six",
		{
			_OO__ ,
			O____ ,
			OOO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0067,    5, "7",                1700, 0x0037,     0x37, "seven",
		{
			OOOO_ ,
			___O_ ,
			__O__ ,
			__O__ ,
			_O___ ,
			_O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0070,    5, "8",                1800, 0x0038,     0x38, "eight",
		{
			_OO__ ,
			O__O_ ,
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0071,    5, "9",                1900, 0x0039,     0x39, "nine",
		{
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
			___O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0072,    3, ":",               13200, 0x003a,     0x3a, "colon",
		{
			___ ,
			OO_ ,
			OO_ ,
			___ ,
			OO_ ,
			OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0073,    3, ";",               13300, 0x003b,     0x3b, "semicolon",
		{
			___ ,
			OO_ ,
			OO_ ,
			___ ,
			OO_ ,
			_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0074,    5, "<",               15500, 0x003c,     0x3c, "less",
		{
			_____ ,
			___O_ ,
			__O__ ,
			_O___ ,
			OOOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0075,    6, "=",               15700, 0x003d,     0x3d, "equal",
		{
			______ ,
			______ ,
			OOOOO_ ,
			______ ,
			OOOOO_ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0076,    5, ">",               16100, 0x003e,     0x3e, "greater",
		{
			_____ ,
			O____ ,
			_O___ ,
			__O__ ,
			OOOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0077,    4, "?",               13100, 0x003f,     0x3f, "question",
		{
			OO__ ,
			__O_ ,
			__O_ ,
			_O__ ,
			____ ,
			_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0100,    6, "@",               13800, 0x0040,     0x40, "at",
		{
			_OOO__ ,
			O___O_ ,
			O_O_O_ ,
			O_OOO_ ,
			O_____ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0101,    6, "A",                2000, 0x0041,     0x41, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0102,    6, "B",                2600, 0x0042,     0x42, NULL,
		{
			OOOO__ ,
			O___O_ ,
			OOOO__ ,
			O___O_ ,
			O___O_ ,
			OOOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0103,    6, "C",                2700, 0x0043,     0x43, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O_____ ,
			O_____ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0104,    6, "D",                3100, 0x0044,     0x44, NULL,
		{
			OOOO__ ,
			_O__O_ ,
			_O__O_ ,
			_O__O_ ,
			_O__O_ ,
			OOOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0105,    6, "E",                3300, 0x0045,     0x45, NULL,
		{
			OOOOO_ ,
			O_____ ,
			OOOO__ ,
			O_____ ,
			O_____ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0106,    6, "F",                3800, 0x0046,     0x46, NULL,
		{
			OOOOO_ ,
			O_____ ,
			OOOO__ ,
			O_____ ,
			O_____ ,
			O_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0107,    6, "G",                3900, 0x0047,     0x47, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O_____ ,
			O__OO_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0110,    6, "H",                4000, 0x0048,     0x48, NULL,
		{
			O___O_ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0111,    4, "I",                4200, 0x0049,     0x49, NULL,
		{
			OOO_ ,
			_O__ ,
			_O__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0112,    5, "J",                4700, 0x004a,     0x4a, NULL,
		{
			___O_ ,
			___O_ ,
			___O_ ,
			___O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0113,    6, "K",                4800, 0x004b,     0x4b, NULL,
		{
			O___O_ ,
			O__O__ ,
			OOO___ ,
			O_O___ ,
			O__O__ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0114,    5, "L",                4900, 0x004c,     0x4c, NULL,
		{
			O____ ,
			O____ ,
			O____ ,
			O____ ,
			O____ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0115,    6, "M",                5000, 0x004d,     0x4d, NULL,
		{
			O___O_ ,
			OO_OO_ ,
			O_O_O_ ,
			O_O_O_ ,
			O___O_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0116,    6, "N",                5100, 0x004e,     0x4e, NULL,
		{
			O___O_ ,
			OO__O_ ,
			O_O_O_ ,
			O__OO_ ,
			O___O_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0117,    6, "O",                5300, 0x004f,     0x4f, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0120,    6, "P",                5900, 0x0050,     0x50, NULL,
		{
			OOOO__ ,
			O___O_ ,
			O___O_ ,
			OOOO__ ,
			O_____ ,
			O_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0121,    6, "Q",                6000, 0x0051,     0x51, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			O_O_O_ ,
			O__O__ ,
			_OO_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0122,    6, "R",                6100, 0x0052,     0x52, NULL,
		{
			OOOO__ ,
			O___O_ ,
			O___O_ ,
			OOOO__ ,
			O__O__ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0123,    5, "S",                6300, 0x0053,     0x53, NULL,
		{
			_OO__ ,
			O__O_ ,
			_O___ ,
			__O__ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0124,    6, "T",                6600, 0x0054,     0x54, NULL,
		{
			OOOOO_ ,
			__O___ ,
			__O___ ,
			__O___ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0125,    6, "U",                6700, 0x0055,     0x55, NULL,
		{
			O___O_ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0126,    6, "V",                7300, 0x0056,     0x56, NULL,
		{
			O___O_ ,
			O___O_ ,
			_O_O__ ,
			_O_O__ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0127,    6, "W",                7400, 0x0057,     0x57, NULL,
		{
			O___O_ ,
			O___O_ ,
			O_O_O_ ,
			O_O_O_ ,
			OO_OO_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0130,    6, "X",                7500, 0x0058,     0x58, NULL,
		{
			O___O_ ,
			_O_O__ ,
			__O___ ,
			__O___ ,
			_O_O__ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0131,    6, "Y",                7800, 0x0059,     0x59, NULL,
		{
			O___O_ ,
			O___O_ ,
			_O_O__ ,
			__O___ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0132,    5, "Z",                8300, 0x005a,     0x5a, NULL,
		{
			OOOO_ ,
			___O_ ,
			__O__ ,
			_O___ ,
			O____ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0133,    4, "[",               18100, 0x005b,     0x5b, "bracketleft",
		{
			OOO_ ,
			O___ ,
			O___ ,
			O___ ,
			O___ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0134,    4, "backslash",       17700, 0x005c,     0x5c, NULL,
		{
			O___ ,
			O___ ,
			_O__ ,
			_O__ ,
			__O_ ,
			__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0135,    4, "]",               18200, 0x005d,     0x5d, "bracketright",
		{
			OOO_ ,
			__O_ ,
			__O_ ,
			__O_ ,
			__O_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0136,    4, "^",               17800, 0x005e,     0x5e, "asciicircum",
		{
			_O__ ,
			O_O_ ,
			____ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0137,    5, "_",               13900, 0x005f,     0x5f, "underscore",
		{
			_____ ,
			_____ ,
			_____ ,
			_____ ,
			_____ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0140,    6, "not",             14100, 0x00ac,     0xac, NULL,
		{
			______ ,
			______ ,
			______ ,
			OOOOO_ ,
			____O_ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0141,    5, "a",                2000, 0x0061,     0x61, NULL,
		{
			_____ ,
			_____ ,
			_OOO_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0142,    5, "b",                2600, 0x0062,     0x62, NULL,
		{
			O____ ,
			O____ ,
			OOO__ ,
			O__O_ ,
			O__O_ ,
			OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0143,    5, "c",                2700, 0x0063,     0x63, NULL,
		{
			_____ ,
			_____ ,
			_OO__ ,
			O____ ,
			O____ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0144,    5, "d",                3100, 0x0064,     0x64, NULL,
		{
			___O_ ,
			___O_ ,
			_OOO_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0145,    5, "e",                3300, 0x0065,     0x65, NULL,
		{
			_____ ,
			_____ ,
			_OO__ ,
			O_OO_ ,
			OO___ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0146,    5, "f",                3800, 0x0066,     0x66, NULL,
		{
			__OO_ ,
			_O___ ,
			_O___ ,
			OOO__ ,
			_O___ ,
			_O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0147,    5, "g",                3900, 0x0067,     0x67, NULL,
		{
			_____ ,
			_OOO_ ,
			O__O_ ,
			_OOO_ ,
			___O_ ,
			OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0150,    5, "h",                4000, 0x0068,     0x68, NULL,
		{
			O____ ,
			O____ ,
			OOO__ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0151,    4, "i",                4200, 0x0069,     0x69, NULL,
		{
			_O__ ,
			____ ,
			OO__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0152,    4, "j",                4700, 0x006a,     0x6a, NULL,
		{
			__O_ ,
			____ ,
			_OO_ ,
			__O_ ,
			__O_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0153,    5, "k",                4800, 0x006b,     0x6b, NULL,
		{
			O____ ,
			O____ ,
			O__O_ ,
			OOO__ ,
			O_O__ ,
			O__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0154,    4, "l",                4900, 0x006c,     0x6c, NULL,
		{
			OO__ ,
			_O__ ,
			_O__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0155,    6, "m",                5000, 0x006d,     0x6d, NULL,
		{
			______ ,
			______ ,
			OOOO__ ,
			O_O_O_ ,
			O_O_O_ ,
			O_O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0156,    5, "n",                5100, 0x006e,     0x6e, NULL,
		{
			_____ ,
			_____ ,
			OOO__ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0157,    5, "o",                5300, 0x006f,     0x6f, NULL,
		{
			_____ ,
			_____ ,
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0160,    5, "p",                5900, 0x0070,     0x70, NULL,
		{
			_____ ,
			_____ ,
			OOO__ ,
			O__O_ ,
			OOO__ ,
			O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0161,    5, "q",                6000, 0x0071,     0x71, NULL,
		{
			_____ ,
			_____ ,
			_OOO_ ,
			O__O_ ,
			_OOO_ ,
			___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0162,    5, "r",                6100, 0x0072,     0x72, NULL,
		{
			_____ ,
			_____ ,
			O_OO_ ,
			OO___ ,
			O____ ,
			O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0163,    5, "s",                6300, 0x0073,     0x73, NULL,
		{
			_____ ,
			_____ ,
			_OOO_ ,
			_O___ ,
			__O__ ,
			OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0164,    5, "t",                6600, 0x0074,     0x74, NULL,
		{
			_O___ ,
			_O___ ,
			OOOO_ ,
			_O___ ,
			_O___ ,
			__OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0165,    5, "u",                6700, 0x0075,     0x75, NULL,
		{
			_____ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0166,    6, "v",                7300, 0x0076,     0x76, NULL,
		{
			______ ,
			______ ,
			O___O_ ,
			O___O_ ,
			_O_O__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0167,    6, "w",                7400, 0x0077,     0x77, NULL,
		{
			______ ,
			______ ,
			O___O_ ,
			O_O_O_ ,
			O_O_O_ ,
			_O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0170,    4, "x",                7500, 0x0078,     0x78, NULL,
		{
			____ ,
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0171,    5, "y",                7800, 0x0079,     0x79, NULL,
		{
			_____ ,
			_____ ,
			O__O_ ,
			_O_O_ ,
			__O__ ,
			OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0172,    5, "z",                8300, 0x007a,     0x7a, NULL,
		{
			_____ ,
			_____ ,
			OOO__ ,
			__O__ ,
			_O___ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0173,    4, "{",               18300, 0x007b,     0x7b, "braceleft",
		{
			_OO_ ,
			_O__ ,
			O___ ,
			O___ ,
			_O__ ,
			_OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0174,    2, "|",               17900, 0x007c,     0x7c, "bar",
		{
			O_ ,
			O_ ,
			O_ ,
			O_ ,
			O_ ,
			O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0175,    4, "}",               18400, 0x007d,     0x7d, "braceright",
		{
			OO__ ,
			_O__ ,
			__O_ ,
			__O_ ,
			_O__ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0176,    6, "~",               14000, 0x007e,     0x7e, "asciitilde",
		{
			______ ,
			_O____ ,
			O_O_O_ ,
			___O__ ,
			______ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0177,    4, "^v",              19100, 0x2195,     0x7f, "up-down",
		{
			_O__ ,
			OOO_ ,
			____ ,
			____ ,
			OOO_ ,
			_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0200,    4, "^3",               1300, 0x00b3,     0xb3, "super-3",
		{
			OO__ ,
			_O__ ,
			__O_ ,
			OOO_ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0201,    6, "sub-w",            7400, 0x24b2,     0x81, NULL,
		{
			______ ,
			______ ,
			______ ,
			______ ,
			O_O_O_ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0202,    6, "GAMMA",            9300, 0x0393,     0x82, NULL,
		{
			OOOOO_ ,
			O___O_ ,
			O_____ ,
			O_____ ,
			O_____ ,
			O_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0203,    6, "DELTA",            9400, 0x0394,     0x83, NULL,
		{
			__O___ ,
			__O___ ,
			_O_O__ ,
			_O_O__ ,
			O___O_ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0204,    6, "D-bar",            3200, 0x00d0,     0xd0, NULL,
		{
			OOOO__ ,
			_O__O_ ,
			OOO_O_ ,
			_O__O_ ,
			_O__O_ ,
			OOOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0205,    6, "d-bar",            3200, 0x00f0,     0xf0, NULL,
		{
			___O__ ,
			__OOO_ ,
			___O__ ,
			_OOO__ ,
			O__O__ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0206,    4, "sub-d",            3100, 0x249f,     0x0e, NULL,
		{
			____ ,
			____ ,
			____ ,
			__O_ ,
			OOO_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0207,    6, "THETA",            9800, 0x0398,     0x86, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0210,    6, "AE",               2500, 0x00c6,     0xc6, NULL,
		{
			_OOOO_ ,
			O_O___ ,
			O_OOO_ ,
			OOO___ ,
			O_O___ ,
			O_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0211,    6, "ae",               2500, 0x00e6,     0xe6, NULL,
		{
			______ ,
			______ ,
			_OOOO_ ,
			O_O_O_ ,
			O_OO__ ,
			_OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0212,    6, "LAMBDA",          10100, 0x039b,     0x88, NULL,
		{
			__O___ ,
			__O___ ,
			_O_O__ ,
			_O_O__ ,
			O___O_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0213,    1, "0213",                0, 0xe100,     0x08, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0214,    1, "0214",                0, 0xe101,     0x09, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0215,    6, "XI",              10400, 0x039e,     0x8d, NULL,
		{
			OOOOO_ ,
			______ ,
			_OOO__ ,
			______ ,
			______ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0216,    6, "sol",             17400, 0x2609,     0x84, NULL,
		{
			______ ,
			_OOO__ ,
			O___O_ ,
			O_O_O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0217,    6, "PI",              10600, 0x03a0,     0x8f, NULL,
		{
			OOOOO_ ,
			_O_O__ ,
			_O_O__ ,
			_O_O__ ,
			_O_O__ ,
			_O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0220,    1, "0220",                0, 0xe102,     0x0a, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0221,    6, "SIGMA",           10800, 0x03a3,     0x91, NULL,
		{
			OOOOO_ ,
			_O____ ,
			__O___ ,
			__O___ ,
			_O____ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0222,    1, "0222",                0, 0xe103,     0x0b, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0223,    1, "0223",                0, 0xe104,     0x0c, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0224,    6, "PHI",             11100, 0x03a6,     0x94, NULL,
		{
			__O___ ,
			_OOO__ ,
			O_O_O_ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0225,    1, "0225",                0, 0xe105,     0x0d, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0226,    6, "PSI",             11300, 0x03a8,     0x96, NULL,
		{
			__O___ ,
			O_O_O_ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0227,    6, "OMEGA",           11400, 0x03a9,     0x97, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_O_O__ ,
			OO_OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0230,    4, "sub-B",            2600, 0x249d,     0x98, NULL,
		{
			____ ,
			____ ,
			____ ,
			OO__ ,
			OOO_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0231,    4, "sub-mu",          10200, 0x00b6,     0x99, NULL,
		{
			____ ,
			____ ,
			____ ,
			O_O_ ,
			OOO_ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0232,    4, "^2",               1200, 0x00b2,     0xb2, "super-2",
		{
			OOO_ ,
			__O_ ,
			_O__ ,
			OOO_ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0233,    6, "sub-infinity",    17300, 0x2088,     0x9b, NULL,
		{
			______ ,
			______ ,
			______ ,
			_O_O__ ,
			O_O_O_ ,
			_O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0234,    4, "^x",               7500, 0x1d61,     0x9c, "super-x",
		{
			O_O_ ,
			_O__ ,
			O_O_ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0235,    6, "^-1",             12400, 0x2078,     0x9d, "reciprocal",
		{
			____O_ ,
			___OO_ ,
			OO__O_ ,
			____O_ ,
			______ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0236,    6, "h-bar",            4100, 0x0127,     0x92, NULL,
		{
			_O____ ,
			OOOO__ ,
			_O____ ,
			_OOO__ ,
			_O__O_ ,
			_O__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0237,    6, "infinity",        17300, 0x221e,     0x85, NULL,
		{
			______ ,
			______ ,
			_O_O__ ,
			O_O_O_ ,
			O_O_O_ ,
			_O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0240,    6, "alpha",            9100, 0x03b1,     0x90, NULL,
		{
			______ ,
			______ ,
			_OO_O_ ,
			O__O__ ,
			O__O__ ,
			_OO_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0241,    5, "beta",             9200, 0x03b2,     0xa1, NULL,
		{
			_O___ ,
			O_O__ ,
			OOO__ ,
			O__O_ ,
			OOO__ ,
			O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0242,    5, "gamma",            9300, 0x03b3,     0xa2, NULL,
		{
			_____ ,
			_O_O_ ,
			O_O__ ,
			__O__ ,
			__O__ ,
			__O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0243,    5, "delta",            9400, 0x03b4,     0x93, NULL,
		{
			__O__ ,
			_O___ ,
			__O__ ,
			_OOO_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0244,    5, "epsilon",          9500, 0x03b5,     0xa4, NULL,
		{
			_____ ,
			_OO__ ,
			O____ ,
			_O___ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0245,    5, "zeta",             9600, 0x03b6,     0x95, NULL,
		{
			OOOO_ ,
			___O_ ,
			__O__ ,
			_O___ ,
			_OOO_ ,
			___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0246,    6, "eta",              9700, 0x03b7,     0xa6, NULL,
		{
			______ ,
			______ ,
			O_OO__ ,
			_O__O_ ,
			_O__O_ ,
			____O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0247,    6, "theta",            9800, 0x03b8,     0xa7, NULL,
		{
			_OO___ ,
			O__O__ ,
			O__O__ ,
			_OOOO_ ,
			O__O__ ,
			_OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0250,    3, "iota",             9900, 0x03b9,     0xa8, NULL,
		{
			___ ,
			___ ,
			O__ ,
			O__ ,
			O__ ,
			OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0251,    5, "kappa",           10000, 0x03ba,     0xa9, NULL,
		{
			_____ ,
			_____ ,
			O_OO_ ,
			OO___ ,
			O_O__ ,
			O__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0252,    5, "lambda",          10100, 0x03bb,     0xaa, NULL,
		{
			O____ ,
			_O___ ,
			__O__ ,
			__O__ ,
			_O_O_ ,
			O__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0253,    5, "mu",              10200, 0x03bc,     0xb5, NULL,
		{
			_____ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			OOOO_ ,
			O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0254,    5, "nu",              10300, 0x03bd,     0x8b, NULL,
		{
			_____ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			O_O__ ,
			OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0255,    5, "xi",              10400, 0x03be,     0xad, NULL,
		{
			OOOO_ ,
			__O__ ,
			_OOO_ ,
			__O__ ,
			_OOO_ ,
			___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0256,    6, "terra",           17500, 0x2641,     0xae, NULL,
		{
			______ ,
			_OOO__ ,
			O_O_O_ ,
			OOOOO_ ,
			O_O_O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0257,    6, "pi",              10600, 0x03c0,     0x60, NULL,
		{
			______ ,
			______ ,
			OOOOO_ ,
			_O_O__ ,
			_O_O__ ,
			_O_OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0260,    6, "rho",             10700, 0x03c1,     0xaf, NULL,
		{
			______ ,
			______ ,
			__OOO_ ,
			_O__O_ ,
			_OOO__ ,
			OO____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0261,    6, "sigma",           10800, 0x03c3,     0x8c, NULL,
		{
			______ ,
			______ ,
			_OOOO_ ,
			O__O__ ,
			O__O__ ,
			_OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0262,    5, "tau",             10900, 0x03c4,     0x89, NULL,
		{
			_____ ,
			_____ ,
			OOOO_ ,
			_O___ ,
			_O___ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0263,    6, "upsilon",         11000, 0x03c5,     0xde, NULL,
		{
			______ ,
			______ ,
			OO__O_ ,
			_O__O_ ,
			_O__O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0264,    6, "phi",             11100, 0x03c6,     0xb4, NULL,
		{
			______ ,
			_OOO__ ,
			O_O_O_ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0265,    6, "chi",             11200, 0x03c7,     0xd4, NULL,
		{
			______ ,
			_OO_O_ ,
			__OO__ ,
			__O___ ,
			_OO___ ,
			O_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0266,    6, "psi",             11300, 0x03c8,     0xb6, NULL,
		{
			______ ,
			______ ,
			O_O_O_ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0267,    6, "omega",           11400, 0x03c9,     0xb7, NULL,
		{
			______ ,
			______ ,
			_O_O__ ,
			O___O_ ,
			O_O_O_ ,
			_O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0270,    4, "sub-0",            1000, 0x2080,     0xb8, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0271,    3, "sub-1",            1100, 0x2081,     0xb9, NULL,
		{
			___ ,
			___ ,
			_O_ ,
			OO_ ,
			_O_ ,
			_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0272,    4, "sub-2",            1200, 0x2082,     0xba, NULL,
		{
			____ ,
			____ ,
			OOO_ ,
			__O_ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0273,    4, "sub-c",            2700, 0x249e,     0xee, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			O___ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0274,    4, "sub-e",            3300, 0x2091,     0xbc, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			OO__ ,
			_OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0275,    4, "sub-n",            5100, 0x2099,     0xbd, NULL,
		{
			____ ,
			____ ,
			____ ,
			____ ,
			OOO_ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0276,    4, "sub-p",            5900, 0x209a,     0xbe, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0277,    4, "sub-u",            6600, 0x1d64,     0xbf, NULL,
		{
			____ ,
			____ ,
			____ ,
			____ ,
			O_O_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0300,    6, "A-grave",          2100, 0x00c0,     0xc0, NULL,
		{
			OO____ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0301,    6, "A-acute",          2200, 0x00c1,     0xc1, NULL,
		{
			___OO_ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0302,    6, "A-tilde",          2300, 0x00c3,     0xc3, NULL,
		{
			_OOO__ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0303,    6, "A-umlaut",         2400, 0x00c4,     0xc4, NULL,
		{
			_O_O__ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0304,    6, "A-dot",            2600, 0x00c2,     0xc2, NULL,
		{
			__O___ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			OOOOO_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0305,    6, "C-acute",          2800, 0x0106,     0xf7, NULL,
		{
			___OO_ ,
			______ ,
			_OOOO_ ,
			O_____ ,
			O_____ ,
			_OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0306,    6, "C-hook",           2900, 0x010c,     0xfe, NULL,
		{
			_OOO__ ,
			______ ,
			_OOOO_ ,
			O_____ ,
			O_____ ,
			_OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0307,    6, "C-cedilla",        3000, 0x00c7,     0xc7, NULL,
		{
			_OOO__ ,
			O___O_ ,
			O_____ ,
			O_____ ,
			_OOOO_ ,
			OO____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0310,    6, "E-grave",          3400, 0x00c8,     0xc8, NULL,
		{
			OO____ ,
			______ ,
			OOOOO_ ,
			OOOO__ ,
			O_____ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0311,    6, "E-acute",          3500, 0x00c9,     0xc9, NULL,
		{
			___OO_ ,
			______ ,
			OOOOO_ ,
			OOOO__ ,
			O_____ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0312,    6, "E-tilde",          3600, 0x0112,     0xca, NULL,
		{
			_OOO__ ,
			______ ,
			OOOOO_ ,
			OOOO__ ,
			O_____ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0313,    6, "E-trema",          3700, 0x00cb,     0xcb, NULL,
		{
			_O_O__ ,
			______ ,
			OOOOO_ ,
			OOOO__ ,
			O_____ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0314,    4, "I-grave",          4300, 0x00cc,     0xcc, NULL,
		{
			OO__ ,
			____ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0315,    4, "I-acute",          4400, 0x00cd,     0xcd, NULL,
		{
			_OO_ ,
			____ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0316,    4, "I-tilde",          4500, 0x0128,     0xce, NULL,
		{
			OOO_ ,
			____ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0317,    4, "I-trema",          4600, 0x00cf,     0xcf, NULL,
		{
			O_O_ ,
			____ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0320,    6, "N-tilde",          5200, 0x00d1,     0xd1, NULL,
		{
			_OOO__ ,
			______ ,
			OO__O_ ,
			O_O_O_ ,
			O__OO_ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0321,    6, "O-grave",          5400, 0x00d2,     0xd2, NULL,
		{
			OO____ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0322,    6, "O-acute",          5500, 0x00d3,     0xd3, NULL,
		{
			___OO_ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0323,    6, "O-tilde",          5600, 0x00d5,     0xd5, NULL,
		{
			_OOO__ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0324,    6, "O-umlaut",         5700, 0x00d6,     0xd6, NULL,
		{
			_O_O__ ,
			______ ,
			_OOO__ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0325,    6, "R-hook",           6200, 0x0158,     0x15, NULL,
		{
			_OOO__ ,
			______ ,
			OOOO__ ,
			O___O_ ,
			OOOO__ ,
			O___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0326,    5, "S-hook",           6400, 0x0160,     0x8a, NULL,
		{
			_OOO_ ,
			_____ ,
			_OOO_ ,
			OO___ ,
			__OO_ ,
			OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0327,    4, "sub-A",            2000, 0x2090,     0x16, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0330,    6, "U-grave",          6800, 0x00d9,     0xd9, NULL,
		{
			_O____ ,
			__O___ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0331,    6, "U-acute",          6900, 0x00da,     0xda, NULL,
		{
			___O__ ,
			__O___ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0332,    6, "U-tilde",          7000, 0x0168,     0x18, NULL,
		{
			_OOO__ ,
			______ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0333,    6, "U-umlaut",         7100, 0x00dc,     0xdc, NULL,
		{
			_O_O__ ,
			______ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0334,    6, "U-dot",            7200, 0x00db,     0xdb, NULL,
		{
			__O___ ,
			______ ,
			O___O_ ,
			O___O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0335,    6, "Y-acute",          7900, 0x00dd,     0xdd, NULL,
		{
			___O__ ,
			__O___ ,
			O___O_ ,
			_O_O__ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0336,    6, "Y-trema",          8100, 0x0178,     0x9f, NULL,
		{
			_O_O__ ,
			______ ,
			O___O_ ,
			_O_O__ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0337,    5, "Z-hook",           8400, 0x017d,     0x8e, NULL,
		{
			OOOO_ ,
			_____ ,
			OOOO_ ,
			__O__ ,
			_O___ ,
			OOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0340,    5, "a-grave",          2100, 0x00e0,     0xe0, NULL,
		{
			OO___ ,
			_____ ,
			_OOO_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0341,    5, "a-acute",          2200, 0x00e1,     0xe1, NULL,
		{
			__OO_ ,
			_____ ,
			_OOO_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0342,    5, "a-tilde",          2300, 0x00e3,     0xe3, NULL,
		{
			OOOO_ ,
			_____ ,
			_OOO_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0343,    5, "a-umlaut",         2400, 0x00e4,     0xe4, NULL,
		{
			_O_O_ ,
			_____ ,
			_OOO_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0344,    5, "a-dot",            2600, 0x00e2,     0xe2, NULL,
		{
			__O__ ,
			_____ ,
			_OOO_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0345,    5, "c-acute",          2800, 0x0107,     0x1c, NULL,
		{
			__OO_ ,
			_____ ,
			_OO__ ,
			O____ ,
			O____ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0346,    5, "c-hook",           2900, 0x010d,     0x1e, NULL,
		{
			OOOO_ ,
			_____ ,
			_OO__ ,
			O____ ,
			O____ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0347,    5, "c-cedilla",        3000, 0x00e7,     0xe7, NULL,
		{
			_____ ,
			_OO__ ,
			O____ ,
			O____ ,
			_OOO_ ,
			OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0350,    5, "e-grave",          3400, 0x00e8,     0xe8, NULL,
		{
			OO___ ,
			_____ ,
			_OO__ ,
			O_OO_ ,
			OO___ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0351,    5, "e-acute",          3500, 0x00e9,     0xe9, NULL,
		{
			__OO_ ,
			_____ ,
			_OO__ ,
			O_OO_ ,
			OO___ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0352,    5, "e-tilde",          3600, 0x0113,     0x1f, NULL,
		{
			OOOO_ ,
			_____ ,
			_OO__ ,
			O_OO_ ,
			OO___ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0353,    5, "e-trema",          3700, 0x00eb,     0xeb, NULL,
		{
			O_O__ ,
			_____ ,
			_OO__ ,
			O_OO_ ,
			OO___ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0354,    4, "i-grave",          4300, 0x00ec,     0xec, NULL,
		{
			OO__ ,
			____ ,
			OO__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0355,    4, "i-acute",          4400, 0x00ed,     0xed, NULL,
		{
			_OO_ ,
			____ ,
			OO__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0356,    4, "i-tilde",          4500, 0x0129,     0xc5, NULL,
		{
			OOO_ ,
			____ ,
			OO__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0357,    4, "i-trema",          4600, 0x00ef,     0xef, NULL,
		{
			O_O_ ,
			____ ,
			OO__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0360,    5, "n-tilde",          5200, 0x00f1,     0xf1, NULL,
		{
			OOOO_ ,
			_____ ,
			OOO__ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0361,    5, "o-grave",          5400, 0x00f2,     0xf2, NULL,
		{
			OO___ ,
			_____ ,
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0362,    5, "o-acute",          5500, 0x00f3,     0xf3, NULL,
		{
			__OO_ ,
			_____ ,
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0363,    5, "o-tilde",          5600, 0x00f5,     0xf5, NULL,
		{
			OOOO_ ,
			_____ ,
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0364,    5, "o-umlaut",         5700, 0x00f6,     0xf6, NULL,
		{
			O__O_ ,
			_____ ,
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0365,    5, "r-hook",           6200, 0x0159,     0xe5, NULL,
		{
			OOOO_ ,
			_____ ,
			O_OO_ ,
			OO___ ,
			O____ ,
			O____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0366,    5, "s-hook",           6400, 0x0161,     0x9a, NULL,
		{
			_OOO_ ,
			_____ ,
			_OOO_ ,
			_O___ ,
			__O__ ,
			OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0367,    4, "sub-k",            4800, 0x2096,     0xea, NULL,
		{
			____ ,
			____ ,
			____ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0370,    5, "u-grave",          6800, 0x00f9,     0xf9, NULL,
		{
			OO___ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0371,    5, "u-acute",          6900, 0x00fa,     0xfa, NULL,
		{
			__OO_ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0372,    5, "u-tilde",          7000, 0x0169,     0xf4, NULL,
		{
			OOOO_ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0373,    5, "u-umlaut",         7100, 0x00fc,     0xfc, NULL,
		{
			O__O_ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0374,    5, "u-dot",            7200, 0x00fb,     0xfb, NULL,
		{
			__O__ ,
			_____ ,
			O__O_ ,
			O__O_ ,
			O__O_ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0375,    5, "y-acute",          7900, 0x00fd,     0xfd, NULL,
		{
			__OO_ ,
			_____ ,
			O__O_ ,
			_O_O_ ,
			__O__ ,
			OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0376,    5, "y-trema",          8100, 0x00ff,     0xff, NULL,
		{
			O__O_ ,
			_____ ,
			O__O_ ,
			_O_O_ ,
			__O__ ,
			OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0377,    5, "z-hook",           8400, 0x017e,     0x9e, NULL,
		{
			OOO__ ,
			_____ ,
			OOO__ ,
			__O__ ,
			_O___ ,
			_OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0400,    1, "small (null)",       -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0401,    4, "small x-bar",        -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			O_O_ ,
			_O__ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0402,    4, "small y-bar",        -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			O_O_ ,
			OOO_ ,
			__O_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0403,    5, "small sqrt",         -1, 0x0000,     0x00, NULL,
		{
			_OOO_ ,
			_O___ ,
			_O___ ,
			OO___ ,
			_O___ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0404,    4, "small integral",     -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			_O__ ,
			_O__ ,
			_O__ ,
			_O__ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0405,    4, "small degree",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0406,    1, "small narrow-space",    -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0407,    5, "small grad",         -1, 0x0000,     0x00, NULL,
		{
			_OOO_ ,
			O____ ,
			O_OO_ ,
			O__O_ ,
			_OOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0410,    4, "small +/-",          -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			OOO_ ,
			_O__ ,
			____ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0411,    4, "small <=",           -1, 0x0000,     0x00, NULL,
		{
			__O_ ,
			_O__ ,
			OOO_ ,
			____ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0412,    4, "small >=",           -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			_O__ ,
			OOO_ ,
			____ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0413,    4, "small !=",           -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			OOO_ ,
			_O__ ,
			OOO_ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0414,    5, "small euro",         -1, 0x0000,     0x00, NULL,
		{
			_OOO_ ,
			O____ ,
			OOO__ ,
			O____ ,
			_OOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0415,    5, "small ->",           -1, 0x0000,     0x00, NULL,
		{
			_O___ ,
			__O__ ,
			OOOO_ ,
			__O__ ,
			_O___ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0416,    5, "small <-",           -1, 0x0000,     0x00, NULL,
		{
			__O__ ,
			_O___ ,
			OOOO_ ,
			_O___ ,
			__O__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0417,    4, "small v",            -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			_O__ ,
			_O__ ,
			OOO_ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0420,    4, "small ^",            -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0421,    4, "small f-shift",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			_O__ ,
			OOO_ ,
			_O__ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0422,    4, "small g-shift",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			OOO_ ,
			__O_ ,
			OO__ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0423,    4, "small h-shift",      -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			OOO_ ,
			O_O_ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0424,    3, "small cmplx",        -1, 0x0000,     0x00, NULL,
		{
			OO_ ,
			O__ ,
			OO_ ,
			___ ,
			___ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0425,    6, "small O-slash",      -1, 0x0000,     0x00, NULL,
		{
			_OOOO_ ,
			O__OO_ ,
			O_O_O_ ,
			OO__O_ ,
			OOOO__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0426,    5, "small o-slash",      -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			_OOO_ ,
			O_OO_ ,
			OO_O_ ,
			OOO__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0427,    6, "small <->",          -1, 0x0000,     0x00, NULL,
		{
			_O____ ,
			OOOOO_ ,
			_O____ ,
			___O__ ,
			OOOOO_ ,
			___O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0430,    4, "small sz",           -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
			OOO_ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0431,    4, "small x-hat",        -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			O_O_ ,
			____ ,
			O_O_ ,
			_O__ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0432,    4, "small y-hat",        -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			O_O_ ,
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0433,    6, "small sub-m",        -1, 0x0000,     0x00, NULL,
		{
			______ ,
			______ ,
			______ ,
			______ ,
			OOOOO_ ,
			O_O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0434,    4, "small times",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			_O__ ,
			O_O_ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0435,    5, "small approx",       -1, 0x0000,     0x00, NULL,
		{
			_O_O_ ,
			O_O__ ,
			_____ ,
			_O_O_ ,
			O_O__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0436,    5, "small pound",        -1, 0x0000,     0x00, NULL,
		{
			_OO__ ,
			_O___ ,
			OOO__ ,
			_O___ ,
			OOOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0437,    6, "small yen",          -1, 0x0000,     0x00, NULL,
		{
			O___O_ ,
			_OOO__ ,
			__O___ ,
			_OOO__ ,
			__O___ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0440,    2, "small  ",            -1, 0x0000,     0x00, NULL,
		{
			__ ,
			__ ,
			__ ,
			__ ,
			__ ,
			__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0441,    2, "small !",            -1, 0x0000,     0x00, NULL,
		{
			O_ ,
			O_ ,
			O_ ,
			__ ,
			O_ ,
			__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0442,    4, "small dblquote",     -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			O_O_ ,
			____ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0443,    6, "small #",            -1, 0x0000,     0x00, NULL,
		{
			_O_O__ ,
			OOOOO_ ,
			_O_O__ ,
			OOOOO_ ,
			_O_O__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0444,    6, "small $",            -1, 0x0000,     0x00, NULL,
		{
			_OOOO_ ,
			O_O___ ,
			_OOO__ ,
			__O_O_ ,
			OOOO__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0445,    4, "small %",            -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			__O_ ,
			_O__ ,
			O___ ,
			__O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0446,    5, "small &",            -1, 0x0000,     0x00, NULL,
		{
			OOO__ ,
			O_O__ ,
			_O___ ,
			O_OO_ ,
			OOO__ ,
			___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0447,    2, "small '",            -1, 0x0000,     0x00, NULL,
		{
			O_ ,
			O_ ,
			__ ,
			__ ,
			__ ,
			__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0450,    3, "small (",            -1, 0x0000,     0x00, NULL,
		{
			_O_ ,
			O__ ,
			O__ ,
			O__ ,
			_O_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0451,    3, "small )",            -1, 0x0000,     0x00, NULL,
		{
			O__ ,
			_O_ ,
			_O_ ,
			_O_ ,
			O__ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0452,    6, "small *",            -1, 0x0000,     0x00, NULL,
		{
			_O_O__ ,
			__O___ ,
			OOOOO_ ,
			__O___ ,
			_O_O__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0453,    4, "small +",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_O__ ,
			OOO_ ,
			_O__ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0454,    3, "small ,",            -1, 0x0000,     0x00, NULL,
		{
			___ ,
			___ ,
			___ ,
			___ ,
			_O_ ,
			O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0455,    4, "small -",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			OOO_ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0456,    2, "small .",            -1, 0x0000,     0x00, NULL,
		{
			__ ,
			__ ,
			__ ,
			__ ,
			O_ ,
			__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0457,    4, "small /",            -1, 0x0000,     0x00, NULL,
		{
			__O_ ,
			__O_ ,
			_O__ ,
			_O__ ,
			O___ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0460,    4, "small 0",            -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0461,    3, "small 1",            -1, 0x0000,     0x00, NULL,
		{
			_O_ ,
			OO_ ,
			_O_ ,
			_O_ ,
			_O_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0462,    4, "small 2",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			__O_ ,
			_OO_ ,
			O___ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0463,    4, "small 3",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			__O_ ,
			_OO_ ,
			__O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0464,    4, "small 4",            -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			O_O_ ,
			OOO_ ,
			__O_ ,
			__O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0465,    4, "small 5",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O___ ,
			OOO_ ,
			__O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0466,    4, "small 6",            -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			O___ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0467,    4, "small 7",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			__O_ ,
			__O_ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0470,    4, "small 8",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O_O_ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0471,    4, "small 9",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O_O_ ,
			OOO_ ,
			__O_ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0472,    2, "small :",            -1, 0x0000,     0x00, NULL,
		{
			__ ,
			O_ ,
			__ ,
			O_ ,
			__ ,
			__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0473,    3, "small ;",            -1, 0x0000,     0x00, NULL,
		{
			___ ,
			___ ,
			_O_ ,
			___ ,
			_O_ ,
			O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0474,    4, "small <",            -1, 0x0000,     0x00, NULL,
		{
			__O_ ,
			_O__ ,
			O___ ,
			_O__ ,
			__O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0475,    4, "small =",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			OOO_ ,
			____ ,
			OOO_ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0476,    4, "small >",            -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			_O__ ,
			__O_ ,
			_O__ ,
			O___ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0477,    4, "small ?",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			__O_ ,
			_OO_ ,
			____ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0500,    5, "small @",            -1, 0x0000,     0x00, NULL,
		{
			_OO__ ,
			O__O_ ,
			O_OO_ ,
			O____ ,
			_OOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0501,    4, "small A",            -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			O_O_ ,
			OOO_ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0502,    4, "small B",            -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0503,    4, "small C",            -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			O___ ,
			O___ ,
			O___ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0504,    4, "small D",            -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0505,    4, "small E",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O___ ,
			OO__ ,
			O___ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0506,    4, "small F",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O___ ,
			OO__ ,
			O___ ,
			O___ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0507,    4, "small G",            -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			O___ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0510,    4, "small H",            -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			O_O_ ,
			OOO_ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0511,    2, "small I",            -1, 0x0000,     0x00, NULL,
		{
			O_ ,
			O_ ,
			O_ ,
			O_ ,
			O_ ,
			__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0512,    4, "small J",            -1, 0x0000,     0x00, NULL,
		{
			__O_ ,
			__O_ ,
			__O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0513,    5, "small K",            -1, 0x0000,     0x00, NULL,
		{
			O__O_ ,
			O_O__ ,
			OO___ ,
			O_O__ ,
			O__O_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0514,    4, "small L",            -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			O___ ,
			O___ ,
			O___ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0515,    6, "small M",            -1, 0x0000,     0x00, NULL,
		{
			O___O_ ,
			OO_OO_ ,
			O_O_O_ ,
			O___O_ ,
			O___O_ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0516,    5, "small N",            -1, 0x0000,     0x00, NULL,
		{
			O__O_ ,
			OO_O_ ,
			O_OO_ ,
			O__O_ ,
			O__O_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0517,    4, "small O",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0520,    4, "small P",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O_O_ ,
			OOO_ ,
			O___ ,
			O___ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0521,    5, "small Q",            -1, 0x0000,     0x00, NULL,
		{
			_OO__ ,
			O__O_ ,
			O__O_ ,
			O_O__ ,
			_O_O_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0522,    4, "small R",            -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0523,    4, "small S",            -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			O___ ,
			_O__ ,
			__O_ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0524,    4, "small T",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			_O__ ,
			_O__ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0525,    4, "small U",            -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0526,    4, "small V",            -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			O_O_ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0527,    6, "small W",            -1, 0x0000,     0x00, NULL,
		{
			O___O_ ,
			O___O_ ,
			O_O_O_ ,
			OO_OO_ ,
			O___O_ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0530,    4, "small X",            -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			O_O_ ,
			_O__ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0531,    4, "small Y",            -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0532,    4, "small Z",            -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			__O_ ,
			_O__ ,
			O___ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0533,    3, "small [",            -1, 0x0000,     0x00, NULL,
		{
			OO_ ,
			O__ ,
			O__ ,
			O__ ,
			OO_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0534,    4, "small backslash",    -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			O___ ,
			_O__ ,
			_O__ ,
			__O_ ,
			__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0535,    3, "small ]",            -1, 0x0000,     0x00, NULL,
		{
			OO_ ,
			_O_ ,
			_O_ ,
			_O_ ,
			OO_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0536,    4, "small ^",            -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			O_O_ ,
			____ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0537,    4, "small _",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			____ ,
			____ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0540,    4, "small `",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			OOO_ ,
			__O_ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0541,    4, "small a",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_OO_ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0542,    4, "small b",            -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0543,    4, "small c",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_OO_ ,
			O___ ,
			O___ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0544,    4, "small d",            -1, 0x0000,     0x00, NULL,
		{
			__O_ ,
			_OO_ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0545,    4, "small e",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_OO_ ,
			O_O_ ,
			OO__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0546,    4, "small f",            -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			_O__ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0547,    4, "small g",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_OO_ ,
			O_O_ ,
			OOO_ ,
			__O_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0550,    4, "small h",            -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0551,    3, "small i",            -1, 0x0000,     0x00, NULL,
		{
			O__ ,
			___ ,
			O__ ,
			O__ ,
			OO_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0552,    3, "small j",            -1, 0x0000,     0x00, NULL,
		{
			_O_ ,
			___ ,
			_O_ ,
			_O_ ,
			_O_ ,
			OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0553,    4, "small k",            -1, 0x0000,     0x00, NULL,
		{
			O___ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0554,    3, "small l",            -1, 0x0000,     0x00, NULL,
		{
			O__ ,
			O__ ,
			O__ ,
			O__ ,
			OO_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0555,    6, "small m",            -1, 0x0000,     0x00, NULL,
		{
			______ ,
			OOOO__ ,
			O_O_O_ ,
			O_O_O_ ,
			O_O_O_ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0556,    4, "small n",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0557,    4, "small o",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0560,    4, "small p",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			OO__ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0561,    4, "small q",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_OO_ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0562,    4, "small r",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_OO_ ,
			O___ ,
			O___ ,
			O___ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0563,    4, "small s",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			OOO_ ,
			O___ ,
			__O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0564,    4, "small t",            -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0565,    4, "small u",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0566,    4, "small v",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0567,    6, "small w",            -1, 0x0000,     0x00, NULL,
		{
			______ ,
			O___O_ ,
			O_O_O_ ,
			O_O_O_ ,
			_O_O__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0570,    4, "small x",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0571,    4, "small y",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			__O_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0572,    4, "small z",            -1, 0x0000,     0x00, NULL,
		{
			____ ,
			OOO_ ,
			__O_ ,
			O___ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0573,    4, "small {",            -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			_O__ ,
			OO__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0574,    2, "small |",            -1, 0x0000,     0x00, NULL,
		{
			O_ ,
			O_ ,
			O_ ,
			O_ ,
			O_ ,
			O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0575,    4, "small }",            -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			_O__ ,
			_OO_ ,
			_O__ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0576,    5, "small ~",            -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			_O_O_ ,
			O_O__ ,
			_____ ,
			_____ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0577,    4, "small ^v",           -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			OOO_ ,
			____ ,
			____ ,
			OOO_ ,
			_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0600,    4, "small ^3",           -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			_O__ ,
			__O_ ,
			OOO_ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0601,    6, "small sub-w",        -1, 0x0000,     0x00, NULL,
		{
			______ ,
			______ ,
			______ ,
			______ ,
			O_O_O_ ,
			OOOOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0602,    4, "small GAMMA",        -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O___ ,
			O___ ,
			O___ ,
			O___ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0603,    5, "small DELTA",        -1, 0x0000,     0x00, NULL,
		{
			___O_ ,
			__OO_ ,
			_O_O_ ,
			O__O_ ,
			OOOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0604,    5, "small D-bar",        -1, 0x0000,     0x00, NULL,
		{
			_OO__ ,
			_O_O_ ,
			OO_O_ ,
			_O_O_ ,
			_OO__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0605,    5, "small d-bar",        -1, 0x0000,     0x00, NULL,
		{
			__O__ ,
			_OOO_ ,
			O_O__ ,
			O_O__ ,
			_OO__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0606,    3, "small sub-d",        -1, 0x0000,     0x00, NULL,
		{
			___ ,
			___ ,
			___ ,
			_O_ ,
			OO_ ,
			OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0607,    5, "small THETA",        -1, 0x0000,     0x00, NULL,
		{
			_OO__ ,
			O__O_ ,
			OOOO_ ,
			O__O_ ,
			_OO__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0610,    5, "small AE",           -1, 0x0000,     0x00, NULL,
		{
			_OOO_ ,
			O_O__ ,
			OOOO_ ,
			O_O__ ,
			O_OO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0611,    6, "small ae",           -1, 0x0000,     0x00, NULL,
		{
			______ ,
			_OOOO_ ,
			O_O_O_ ,
			O_OO__ ,
			_OOOO_ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0612,    4, "small LAMBDA",       -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			_O__ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0613,    1, "small 0213",         -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0614,    1, "small 0214",         -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0615,    5, "small XI",           -1, 0x0000,     0x00, NULL,
		{
			OOOO_ ,
			_____ ,
			_OO__ ,
			_____ ,
			OOOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0616,    6, "small sol",          -1, 0x0000,     0x00, NULL,
		{
			______ ,
			_OOO__ ,
			O___O_ ,
			O_O_O_ ,
			O___O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0617,    4, "small PI",           -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0620,    1, "small 0220",         -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0621,    5, "small SIGMA",        -1, 0x0000,     0x00, NULL,
		{
			OOOO_ ,
			_O___ ,
			__O__ ,
			_O___ ,
			OOOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0622,    1, "small 0222",         -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0623,    1, "small 0223",         -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0624,    6, "small PHI",          -1, 0x0000,     0x00, NULL,
		{
			__O___ ,
			OOOOO_ ,
			O_O_O_ ,
			OOOOO_ ,
			__O___ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0625,    1, "small 0225",         -1, 0x0000,     0x00, NULL,
		{
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
			_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0626,    6, "small PSI",          -1, 0x0000,     0x00, NULL,
		{
			O_O_O_ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
			__O___ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0627,    5, "small OMEGA",        -1, 0x0000,     0x00, NULL,
		{
			_OO__ ,
			O__O_ ,
			O__O_ ,
			_OO__ ,
			OOOO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0630,    4, "small sub-B",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			OO__ ,
			OOO_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0631,    4, "small sub-mu",       -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			O_O_ ,
			OOO_ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0632,    3, "small ^2",           -1, 0x0000,     0x00, NULL,
		{
			OO_ ,
			_O_ ,
			O__ ,
			OO_ ,
			___ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0633,    6, "small sub-infinity",    -1, 0x0000,     0x00, NULL,
		{
			______ ,
			______ ,
			______ ,
			_O_O__ ,
			O_O_O_ ,
			_O_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0634,    4, "small ^x",           -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			_O__ ,
			O_O_ ,
			____ ,
			____ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0635,    5, "small ^-1",          -1, 0x0000,     0x00, NULL,
		{
			___O_ ,
			OO_O_ ,
			___O_ ,
			_____ ,
			_____ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0636,    5, "small h-bar",        -1, 0x0000,     0x00, NULL,
		{
			_O___ ,
			OOO__ ,
			_O___ ,
			_OOO_ ,
			_O_O_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0637,    6, "small infinity",     -1, 0x0000,     0x00, NULL,
		{
			______ ,
			_O_O__ ,
			O_O_O_ ,
			O_O_O_ ,
			_O_O__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0640,    5, "small alpha",        -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			_O_O_ ,
			O_O__ ,
			O_O__ ,
			_O_O_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0641,    4, "small beta",         -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
			OO__ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0642,    4, "small gamma",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			_O__ ,
			_O__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0643,    4, "small delta",        -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			O___ ,
			_O__ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0644,    4, "small epsilon",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			O___ ,
			_OO_ ,
			O___ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0645,    4, "small zeta",         -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			__O_ ,
			_O__ ,
			O___ ,
			OOO_ ,
			__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0646,    5, "small eta",          -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			OOO__ ,
			_O_O_ ,
			_O_O_ ,
			___O_ ,
			___O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0647,    5, "small theta",        -1, 0x0000,     0x00, NULL,
		{
			OOO__ ,
			O_O__ ,
			_OOO_ ,
			O_O__ ,
			OOO__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0650,    3, "small iota",         -1, 0x0000,     0x00, NULL,
		{
			___ ,
			O__ ,
			O__ ,
			O__ ,
			OO_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0651,    4, "small kappa",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0652,    4, "small lambda",       -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			__O_ ,
			__O_ ,
			_OO_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0653,    4, "small mu",           -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0654,    4, "small nu",           -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			O_O_ ,
			OO__ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0655,    4, "small xi",           -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			_O__ ,
			OOO_ ,
			_O__ ,
			OOO_ ,
			__O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0656,    6, "small terra",        -1, 0x0000,     0x00, NULL,
		{
			______ ,
			_OOO__ ,
			O_O_O_ ,
			OOOOO_ ,
			O_O_O_ ,
			_OOO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0657,    5, "small pi",           -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			OOOO_ ,
			O_O__ ,
			O_O__ ,
			O_OO_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0660,    5, "small rho",          -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			__OO_ ,
			_O_O_ ,
			_OOO_ ,
			_O___ ,
			OO___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0661,    5, "small sigma",        -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			_OOO_ ,
			O_O__ ,
			O_O__ ,
			_O___ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0662,    4, "small tau",          -1, 0x0000,     0x00, NULL,
		{
			____ ,
			OOO_ ,
			_O__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0663,    5, "small upsilon",      -1, 0x0000,     0x00, NULL,
		{
			_____ ,
			OO_O_ ,
			_O_O_ ,
			_O_O_ ,
			_OO__ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0664,    6, "small phi",          -1, 0x0000,     0x00, NULL,
		{
			______ ,
			_OOO__ ,
			O_O_O_ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0665,    4, "small chi",          -1, 0x0000,     0x00, NULL,
		{
			____ ,
			O_O_ ,
			O_O_ ,
			_O__ ,
			O_O_ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0666,    6, "small psi",          -1, 0x0000,     0x00, NULL,
		{
			______ ,
			O_O_O_ ,
			O_O_O_ ,
			_OOO__ ,
			__O___ ,
			__O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0667,    6, "small omega",        -1, 0x0000,     0x00, NULL,
		{
			______ ,
			_O_O__ ,
			O___O_ ,
			O_O_O_ ,
			_O_O__ ,
			______ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0670,    4, "small sub-0",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0671,    3, "small sub-1",        -1, 0x0000,     0x00, NULL,
		{
			___ ,
			___ ,
			_O_ ,
			OO_ ,
			_O_ ,
			_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0672,    3, "small sub-2",        -1, 0x0000,     0x00, NULL,
		{
			___ ,
			___ ,
			OO_ ,
			_O_ ,
			O__ ,
			OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0673,    3, "small sub-c",        -1, 0x0000,     0x00, NULL,
		{
			___ ,
			___ ,
			___ ,
			OO_ ,
			O__ ,
			OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0674,    4, "small sub-e",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			_OO_ ,
			O_O_ ,
			OO__ ,
			_OO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0675,    4, "small sub-n",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			____ ,
			OOO_ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0676,    4, "small sub-p",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0677,    4, "small sub-u",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			____ ,
			O_O_ ,
			OOO_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0700,    4, "small A-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0701,    4, "small A-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0702,    4, "small A-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0703,    4, "small A-umlaut",     -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0704,    4, "small A-dot",        -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0705,    4, "small C-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			OOO_ ,
			O___ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0706,    4, "small C-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OOO_ ,
			O___ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0707,    4, "small C-cedilla",    -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			O___ ,
			O___ ,
			O___ ,
			_OO_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0710,    4, "small E-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			OOO_ ,
			OO__ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0711,    4, "small E-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			OOO_ ,
			OO__ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0712,    4, "small E-filde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OOO_ ,
			OO__ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0713,    4, "small E-trema",      -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			OOO_ ,
			OO__ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0714,    3, "small I-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO_ ,
			___ ,
			_O_ ,
			_O_ ,
			_O_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0715,    3, "small I-acute",      -1, 0x0000,     0x00, NULL,
		{
			OO_ ,
			___ ,
			O__ ,
			O__ ,
			O__ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0716,    4, "small I-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			_O__ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0717,    4, "small I-trema",      -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			_O__ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0720,    5, "small N-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOOO_ ,
			_____ ,
			OO_O_ ,
			O_OO_ ,
			O__O_ ,
			_____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0721,    4, "small O-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0722,    4, "small O-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0723,    4, "small O-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0724,    4, "small O-umlaut",     -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			OOO_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0725,    4, "small R-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OO__ ,
			OO__ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0726,    4, "small S-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			_OO_ ,
			_O__ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0727,    4, "small sub-A",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			OOO_ ,
			OOO_ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0730,    4, "small U-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0731,    4, "small U-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0732,    4, "small U-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0733,    4, "small U-umlaut",     -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0734,    4, "small U-dot",        -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			____ ,
			O_O_ ,
			O_O_ ,
			OOO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0735,    4, "small Y-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0736,    4, "small Y-trema",      -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			O_O_ ,
			_O__ ,
			_O__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0737,    4, "small Z-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OO__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0740,    4, "small a-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			_OO_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0741,    4, "small a-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			_OO_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0742,    4, "small a-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			_OO_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0743,    4, "small a-umlaut",     -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			_OO_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0744,    4, "small a-dot",        -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			____ ,
			_OO_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0745,    4, "small c-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			OOO_ ,
			O___ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0746,    4, "small c-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OOO_ ,
			O___ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0747,    4, "small c-cedilla",    -1, 0x0000,     0x00, NULL,
		{
			____ ,
			_OO_ ,
			O___ ,
			O___ ,
			_OO_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0750,    4, "small e-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			OOO_ ,
			OO__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0751,    4, "small e-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			OOO_ ,
			OO__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0752,    4, "small e-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OOO_ ,
			OO__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0753,    4, "small e-trema",      -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			OOO_ ,
			OO__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0754,    4, "small i-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			_O__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0755,    3, "small i-acute",      -1, 0x0000,     0x00, NULL,
		{
			OO_ ,
			___ ,
			O__ ,
			O__ ,
			OO_ ,
			___ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0756,    4, "small i-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			_O__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0757,    4, "small i-trema",      -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			_O__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0760,    4, "small n-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OO__ ,
			O_O_ ,
			O_O_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0761,    4, "small o-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			OO__ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0762,    4, "small o-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			OO__ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0763,    4, "small o-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OO__ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0764,    4, "small o-umlaut",     -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			OO__ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0765,    4, "small r-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			_OO_ ,
			O___ ,
			O___ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0766,    4, "small s-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			_OO_ ,
			_O__ ,
			OO__ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0767,    4, "small sub-k",        -1, 0x0000,     0x00, NULL,
		{
			____ ,
			____ ,
			____ ,
			O_O_ ,
			OO__ ,
			O_O_ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0770,    4, "small u-grave",      -1, 0x0000,     0x00, NULL,
		{
			OO__ ,
			____ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0771,    4, "small u-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0772,    4, "small u-tilde",      -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0773,    4, "small u-umlaut",     -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0774,    4, "small u-dot",        -1, 0x0000,     0x00, NULL,
		{
			_O__ ,
			____ ,
			O_O_ ,
			O_O_ ,
			_OO_ ,
			____ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0775,    4, "small y-acute",      -1, 0x0000,     0x00, NULL,
		{
			_OO_ ,
			____ ,
			O_O_ ,
			OOO_ ,
			__O_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0776,    4, "small y-trema",      -1, 0x0000,     0x00, NULL,
		{
			O_O_ ,
			____ ,
			O_O_ ,
			OOO_ ,
			__O_ ,
			OO__ ,
		}
	},

/*	  octal width  name               sort  Unicode  Windows  UnicodeName */
	{ 0777,    4, "small z-hook",       -1, 0x0000,     0x00, NULL,
		{
			OOO_ ,
			____ ,
			OO__ ,
			_O__ ,
			_OO_ ,
			____ ,
		}
	},

